services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    container_name: spring-micrometer-app

  prometheus:
    build:
      context: ./observability/prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    container_name: prometheus

  grafana:
    build:
      context: ./observability/grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: grafana
