services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8081"
    ports:
      - "8080:8080"
    container_name: spring-micrometer-app

  mock-requests:
    build:
      context: ./observability/mockRequests
      dockerfile: Dockerfile
    container_name: http-request-bot

  prometheus:
    build:
      context: ./observability/prometheus
      dockerfile: Dockerfile
    expose:
      - "9090"
    container_name: prometheus

  grafana:
    build:
      context: ./observability/grafana
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: grafana
